services:
  tpf-score-bot:
    container_name: tpf-score-bot
    build: .
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - your_network
    ports:
      - 9099:9099
    volumes:
      - /DATA/apps/tpf-score-bot/config/db:/usr/src/app/data

networks:
  your_network:
    external: true
